apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ml-sample-addition
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-sample-addition
    spec:
      containers:
      - name: sample-addition-service
        image: aishwaryashinde/sampleadditionservice:BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ml-sample-addition-service
  name: ml-sample-addition-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: ml-sample-addition
  type: LoadBalancer
